# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIftBcuo9YF9S14BJ28h41KgpJke2tRn
"""

import pandas as pd
from sklearn.model_selection import train_test_split

d = pd.read_csv('/content/train (2).csv')
print(d)

y = d['price_range']
print(y)

x = d.drop('price_range',axis=1)
print(x)

dn = x-x.min()/x.max()-x.min()
print(dn)

xtrain,xtest,ytrain,ytest = train_test_split(dn,y,test_size=0.2, random_state=30)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)

d = pd.read_csv('/content/sample_data/california_housing_train.csv')
print(d)

d.dtypes

d.shape

y = d['median_house_value']
print(y)

x = d.drop('median_house_value',axis=1)
print(x)

d.isnull().sum()
d.fillna(0, inplace=True)

dn = x-x.min()/x.max()-x.min()
print(dn)

xtrain,xtest,ytrain,ytest = train_test_split(dn,y,test_size=0.2, random_state=30)
print(xtrain)
print(xtest)
print(ytrain)
print(ytest)